schemaVersion: 2.1.0
metadata:
  name: python-hello-world
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      volumeMounts:
        - name: venv
          path: /home/user/.venv
        - name: home
          path: /home/jovyan/work
      memoryLimit: 2G
      mountSources: true
  - name: venv
    volume:
      size: 1G
  - name: home
    volume:
      size: 512Mi
  - name: conda
    container:
      image: dso-quay-registry-quay-quay-enterprise.apps.ocp1.azure.dso.digital.mod.uk/george_cairns/dayglo-jupyterlab
      mountSources: true
      env:
        - name: NOTEBOOK_ARGS
          value: --notebook-dir=/projects/devspaces-test # --NotebookApp.token='blahdeblah'
      volumeMounts:
        - name: home
          path: /home/jovyan/work
      endpoints:
      - name: jupyterlab
        attributes:
          urlRewriteSupported: false
        targetPort: 8888
        protocol: https
        secure: true
        exposure: public
      memoryLimit: 2G
