schemaVersion: 2.2.0
metadata:
  name: python-hello-world
components:
  - name: venv
    volume:
      size: 1G
  - name: home
    volume:
      size: 512Mi
  - name: conda
    container:
      image: quay.io/mloriedo/cloud-dev-images:jupyterlab
      mountSources: true
      env:
        - name: NOTEBOOK_ARGS
          value: --notebook-dir=/projects/devspaces-test # --NotebookApp.token='blahdeblah'
      volumeMounts:
        - name: home
          path: /home/jovyan/work
        - name: venv
          path: /home/jovyan/.venv
      endpoints:
      - name: jupyterlab
        attributes:
          urlRewriteSupported: false
        targetPort: 8888
        protocol: https
        secure: true
        exposure: public
      memoryLimit: 2G
commands:
  - id: start-notebook
    exec:
      label: Start Notebook
      commandLine: nohup start-notebook.sh &
      component: conda
events:
    postStart:
      - start-notebook
