FROM jupyter/scipy-notebook:2023-02-28

USER root

RUN conda install -c conda-forge jupyterlab

RUN chgrp -R root /home/ \
    && chgrp -R root /opt/conda

# Install curl and ca_certificates (required to install nodejs)
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    ca-certificates \
    curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# The install of nodejs 16 + the export of VSCODE_NODEJS_RUNTIME_DIR
# environment variable are required on base images that have openssl v3 or higher.
# This is a temporary workaround for https://github.com/eclipse/che/issues/21778
# See also https://github.com/che-incubator/che-code/pull/120
RUN \
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
export NVM_DIR="$HOME/.nvm" && \
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
nvm install 16.20.0

ENV VSCODE_NODEJS_RUNTIME_DIR="$HOME/.nvm/versions/node/v16.20.0/bin/"

USER 1000
